---
driver:
  name: ec2
  associate_public_ip: true

provisioner:
  name: shell

transport:
  username: ubuntu

platforms:
- name: ubuntu-redis
  driver:
    image_search:
      owner-id: "938620692197"
      name: "slav-ubuntu-redis-*"

verifier:
  name: inspec

suites:
  - name: default
